name: Codecov

on:
  push:
    branches: [ ui ]
  pull_request:
    branches: [ ui ]

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
        	./gradlew clean test
    		bash <(curl -s https://codecov.io/bash) -f "app/build/reports/jacoco/testDebugUnitTest.exec"
  	  env:
    		JVM_OPTS: -Xmx1024m
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
