name: Codecov

on:
  push:
    branches: [ ui ]
  pull_request:
    branches: [ ui ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: 1.11
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      - name: Run tests and generate coverage report
        run: |
          ./gradlew clean test
          bash <(curl -s https://codecov.io/bash) -f "app/build/reports/jacoco/testDebugUnitTest.exec"
        env:
          JVM_OPTS: -Xmx1024m
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
